### ISSUE TITLE
Releasing to Maven Central

### ISSUE THREAD

**Issue by smiklosovic** [GenesysPureEngagePremise/cassandra-es-index#10]
Hi,

it would be nice if this plugin was released in Maven Central so I do not have to build this when I want to use it and I would just grab a JAR.

**Comment by gartcimore** [comment]
This will need the following :
* an account on sonatype (create one [https://issues.sonatype.org/secure/Signup!default.jspa](here)
* creating a ticket [https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134](here)
* having a proper groupid (read policies [https://central.sonatype.org/pages/choosing-your-coordinates.html](here) 
* having enough metadata [https://central.sonatype.org/pages/requirements.html#sufficient-metadata](read more here)

For the  proper groupid, the current is correct, so this step is done

**Comment by gartcimore** [comment]
[https://help.github.com/en/github/managing-packages-with-github-package-registry/configuring-apache-maven-for-use-with-github-package-registry](configuring github registry)

**Comment by gartcimore** [comment]
I propose to rename group id from com.genesyslab.webme.commons to com.genesys 
Shorter, respect the rules and simpler to remember
see https://github.com/GenesysPureEngagePremise/cassandra-es-index/pull/17

**Comment by gartcimore** [comment]
created https://issues.sonatype.org/browse/OSSRH-53956

**Comment by jhberthemet** [comment]
Good for renaming, and it will help us making a difference between internal and external builds.

**Comment by gartcimore** [comment]
published https://search.maven.org/artifact/com.genesys/es-index/9.1.002.00/jar
