### ISSUE TITLE
support newest version of jdk

### ISSUE THREAD

**Issue by gartcimore** [GenesysPureEngagePremise/cassandra-es-index#19]
Maybe it should be able to support another version of jdk

**Comment by jhberthemet** [comment]
For now we only support Cassandra 3.11 that itself only supports Java 8.

**Comment by gartcimore** [comment]
> For now we only support Cassandra 3.11 that itself only supports Java 8.

yes, that's why we have #6 Support for Cassandra 4.x
Basic pom configuration is done and seems ok. Tests fails because of Cassandra (see branch jdk11 )

**Comment by paolodedo** [comment]
@jhberthemet , @gartcimore 
Cassandra-4.0-beta3 is out, what about its integration? Is it only matter of time, waiting for its final release?

Thanks.

**Comment by fenneclabs** [comment]
@paolodedo for now there is no plan to support Cassandra 4.x. We'll add support for ES 7.x soon.

**Comment by jhberthemet** [comment]
@paolodedo for now there is no plan to support Cassandra 4.x. We'll add support for ES 7.x soon.

**Comment by jhberthemet** [comment]
Cassandra 4.0.x only support JDK 1.8.x for build and runtime so this project stays on the same version.
If you're still interested @paolodedo version with support for Cassandra 4.0.x is out now.
