### ISSUE TITLE
Cassandra fails to start due to license expired at Elasticsearch

### ISSUE THREAD

**Issue by detapundit** [GenesysPureEngagePremise/cassandra-es-index#31]
Hi Team,

We are using cassandra-es-index plugin in our setup.

We have Cassandra V3 and Elasticsearch V6 cluster. It was working fine untill Elasticsearch license expired and cassandra would refuse to start unless the license issue is fixed. Below is the exception we got:
Caused by: com.genesyslab.webme.commons.index.requests.EsRequestExecutionException: 403:{"root_cause":[{"type":"security_exception","reason":"current license is non-compliant for [security]","license.expired.feature":"security"}],"type":"security_exception","reason":"current license is non-compliant for [security]","license.expired.feature":"security"}

Jar file used: wcc-es-index-9.1.001.01-jar-with-dependencies.jar

Wanted to check with you how we can bypass Elasticsearch license check so that cassandra service can start irrespective of the Elasticsearch license status.

**Comment by jhberthemet** [comment]
Hi,

You should to use the dummy=true option, this will disable the es-index and should allow Cassandra to start again. For example -Dgenesys-es-dummy=true or dummy=true in es-index.properties, or check the README.md for other ways to set options.

**Comment by detapundit** [comment]
Thanks for the update.

Is there any other option which will allow to use es index even with expired license and still allow cassandra to start

**Comment by jhberthemet** [comment]
This is more an Elasticsearch issue, it will refuse all requests if the license issue is not fixed. The ES plugin can't work without a functional ES. So you can either fix the ES issue or use the dummy mode. Dummy mode will return an empty result when searching and will skip writes to ES so your data will become out of sync and you'll need to rebuild the index once ES is fixed.
