### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by silviucpp** [GenesysPureEngagePremise/cassandra-es-index#32]
Hello,

Is this project still alive ? I mean there is any plan to bring it up to date with last Cassandra and ELS ?

Silviu

**Comment by jhberthemet** [comment]
Hi @silviucpp, 

We're transitioning to cloud offerings so this project won't get new features. However I pushed the latest version that adds support for Cassandra 4.0.x. There is no plan to support ES 8.x.
